# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://sanketcn.github.io/forecast_template/"

git_url = "https://github.com/sanketcn/forecast_template/tree/master/"

def custom_doc_links(name): return None
